services:
  - type: web
    name: pixel3d-galeria
    runtime: node
    rootDir: galeria
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: UPLOAD_PASSWORD
        sync: false          # Render vai pedir este valor manualmente (não fica no git!)
      - key: NODE_ENV
        value: production
